changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🏗️ Features & Capabilities
      labels:
        - feature
        - enhancement
    - title: 🩹 Fixes & Patches
      labels:
        - fix
        - bug
    - title: 🏎️ Performance Tuning
      labels:
        - performance
        - optimization
    - title: 📜 Documentation
      labels:
        - docs
        - documentation
    - title: 🧹 Chores & Maintenance
      labels:
        - chore
        - maintenance
        - refactor
        - dependencies
    - title: 🔬 Testing & Coverage
      labels:
        - test
        - testing
