import glob
from datetime import datetime

_radar_info = {
    'KABR': {'wfo': 'KABR', 'region': 3},
    'KABX': {'wfo': 'KABQ', 'region': 5},
    'KAKQ': {'wfo': 'KAKQ', 'region': 1},
    'KAMA': {'wfo': 'KAMA', 'region': 4},
    'KAMX': {'wfo': 'KMFL', 'region': 2},
    'KAPX': {'wfo': 'KAPX', 'region': 3},
    'KARX': {'wfo': 'KARX', 'region': 3},
    'KATX': {'wfo': 'KSEW', 'region': 6},
    'KBBW': {'wfo': 'KLBF', 'region': 3},
    'KBBX': {'wfo': 'KSTO', 'region': 6},
    'KBGM': {'wfo': 'KBGM', 'region': 1},
    'KBHX': {'wfo': 'KEKA', 'region': 6},
    'KBIS': {'wfo': 'KBIS', 'region': 3},
    'KBLX': {'wfo': 'KBYZ', 'region': 5},
    'KBMX': {'wfo': 'KBMX', 'region': 4},
    'KBOX': {'wfo': 'KBOX', 'region': 1},
    'KBRO': {'wfo': 'KBRO', 'region': 4},
    'KBUF': {'wfo': 'KBUF', 'region': 1},
    'KBYX': {'wfo': 'KKEY', 'region': 2},
    'KCAE': {'wfo': 'KCAE', 'region': 2},
    'KCBW': {'wfo': 'KCAR', 'region': 1},
    'KCBX': {'wfo': 'KBOI', 'region': 5},
    'KCCX': {'wfo': 'KCTP', 'region': 1},
    'KCLE': {'wfo': 'KCLE', 'region': 1},
    'KCLX': {'wfo': 'KCHS', 'region': 2},
    'KCRP': {'wfo': 'KCRP', 'region': 4},
    'KCXX': {'wfo': 'KBTV', 'region': 1},
    'KCYS': {'wfo': 'KCYS', 'region': 5},
    'KDAX': {'wfo': 'KSTO', 'region': 6},
    'KDDC': {'wfo': 'KDDC', 'region': 3},
    'KDFX': {'wfo': 'KEWX', 'region': 4},
    'KDGX': {'wfo': 'KJAN', 'region': 4},
    'KDIX': {'wfo': 'KPHI', 'region': 1},
    'KDLH': {'wfo': 'KDLH', 'region': 3},
    'KDMX': {'wfo': 'KDMX', 'region': 3},
    'KDOX': {'wfo': 'KAKQ', 'region': 1},
    'KDTX': {'wfo': 'KDTX', 'region': 3},
    'KDVN': {'wfo': 'KDVN', 'region': 3},
    'KDYX': {'wfo': 'KSJT', 'region': 4},
    'KEAX': {'wfo': 'KEAX', 'region': 3},
    'KEMX': {'wfo': 'KTWC', 'region': 5},
    'KENX': {'wfo': 'KALY', 'region': 1},
    'KEOX': {'wfo': 'KTAE', 'region': 2},
    'KEPZ': {'wfo': 'KEPZ', 'region': 4},
    'KESX': {'wfo': 'KVEF', 'region': 5},
    'KEVX': {'wfo': 'KMOB', 'region': 4},
    'KEWX': {'wfo': 'KEWX', 'region': 4},
    'KEYX': {'wfo': 'KVEF', 'region': 5},
    'KFCX': {'wfo': 'KRNK', 'region': 1},
    'KFDR': {'wfo': 'KOUN', 'region': 4},
    'KFDX': {'wfo': 'KABQ', 'region': 5},
    'KFFC': {'wfo': 'KFFC', 'region': 2},
    'KFSD': {'wfo': 'KFSD', 'region': 3},
    'KFSX': {'wfo': 'KFGZ', 'region': 5},
    'KFTG': {'wfo': 'KBOU', 'region': 5},
    'KFWS': {'wfo': 'KFWD', 'region': 4},
    'KGGW': {'wfo': 'KGGW', 'region': 5},
    'KGJX': {'wfo': 'KGJT', 'region': 5},
    'KGLD': {'wfo': 'KGLD', 'region': 3},
    'KGRB': {'wfo': 'KGRB', 'region': 3},
    'KGRK': {'wfo': 'KFWD', 'region': 4},
    'KGRR': {'wfo': 'KGRR', 'region': 3},
    'KGSP': {'wfo': 'KGSP', 'region': 2},
    'KGWX': {'wfo': 'KJAN', 'region': 4},
    'KGYX': {'wfo': 'KGYX', 'region': 1},
    'KHDC': {'wfo': 'KHDC', 'region': 4},
    'KHDX': {'wfo': 'KEPZ', 'region': 4},
    'KHGX': {'wfo': 'KHGX', 'region': 4},
    'KHNX': {'wfo': 'KHNX', 'region': 6},
    'KHPX': {'wfo': 'KPAH', 'region': 3},
    'KHTX': {'wfo': 'KHUN', 'region': 4},
    'KICT': {'wfo': 'KICT', 'region': 3},
    'KICX': {'wfo': 'KSLC', 'region': 5},
    'KILN': {'wfo': 'KILN', 'region': 1},
    'KILX': {'wfo': 'KILX', 'region': 3},
    'KIND': {'wfo': 'KIND', 'region': 3},
    'KINX': {'wfo': 'KTSA', 'region': 4},
    'KIWA': {'wfo': 'KPSR', 'region': 5},
    'KIWX': {'wfo': 'KIWX', 'region': 3},
    'KJAX': {'wfo': 'KJAX', 'region': 2},
    'KJGX': {'wfo': 'KFFC', 'region': 2},
    'KJKL': {'wfo': 'KJKL', 'region': 3},
    'KLBB': {'wfo': 'KLUB', 'region': 4},
    'KLCH': {'wfo': 'KLCH', 'region': 4},
    'KLGX': {'wfo': 'KSEW', 'region': 6},
    'KLNX': {'wfo': 'KLBF', 'region': 3},
    'KLOT': {'wfo': 'KLOT', 'region': 3},
    'KLRX': {'wfo': 'KLKN', 'region': 5},
    'KLSX': {'wfo': 'KLSX', 'region': 3},
    'KLTX': {'wfo': 'KILM', 'region': 2},
    'KLVX': {'wfo': 'KLMK', 'region': 3},
    'KLWX': {'wfo': 'KLWX', 'region': 1},
    'KLZK': {'wfo': 'KLZK', 'region': 4},
    'KMAF': {'wfo': 'KMAF', 'region': 4},
    'KMAX': {'wfo': 'KMFR', 'region': 6},
    'KMBX': {'wfo': 'KBIS', 'region': 3},
    'KMHX': {'wfo': 'KMHX', 'region': 2},
    'KMKX': {'wfo': 'KMKX', 'region': 3},
    'KMLB': {'wfo': 'KMLB', 'region': 2},
    'KMOB': {'wfo': 'KMOB', 'region': 4},
    'KMPX': {'wfo': 'KMPX', 'region': 3},
    'KMQT': {'wfo': 'KMQT', 'region': 3},
    'KMRX': {'wfo': 'KMRX', 'region': 4},
    'KMSX': {'wfo': 'KMSO', 'region': 5},
    'KMTX': {'wfo': 'KSLC', 'region': 5},
    'KMUX': {'wfo': 'KMTR', 'region': 6},
    'KMVX': {'wfo': 'KFGF', 'region': 3},
    'KMXX': {'wfo': 'KBMX', 'region': 4},
    'KNKX': {'wfo': 'KSGX', 'region': 6},
    'KNQA': {'wfo': 'KMEG', 'region': 4},
    'KOAX': {'wfo': 'KOAX', 'region': 3},
    'KOHX': {'wfo': 'KOHX', 'region': 4},
    'KOKX': {'wfo': 'KOKX', 'region': 1},
    'KOTX': {'wfo': 'KOTX', 'region': 6},
    'KPAH': {'wfo': 'KPAH', 'region': 3},
    'KPBZ': {'wfo': 'KPBZ', 'region': 1},
    'KPDT': {'wfo': 'KPDT', 'region': 6},
    'KPOE': {'wfo': 'KLCH', 'region': 4},
    'KPUX': {'wfo': 'KPUB', 'region': 5},
    'KRAX': {'wfo': 'KRAH', 'region': 2},
    'KRGX': {'wfo': 'KREV', 'region': 5},
    'KRIW': {'wfo': 'KRIW', 'region': 5},
    'KRLX': {'wfo': 'KRLX', 'region': 1},
    'KRTX': {'wfo': 'KPQR', 'region': 6},
    'KSFX': {'wfo': 'KPIH', 'region': 5},
    'KSGF': {'wfo': 'KSGF', 'region': 3},
    'KSHV': {'wfo': 'KSHV', 'region': 4},
    'KSJT': {'wfo': 'KSJT', 'region': 4},
    'KSOX': {'wfo': 'KSGX', 'region': 6},
    'KSRX': {'wfo': 'KTSA', 'region': 4},
    'KTBW': {'wfo': 'KTBW', 'region': 2},
    'KTFX': {'wfo': 'KTFX', 'region': 5},
    'KTLH': {'wfo': 'KTAE', 'region': 2},
    'KTLX': {'wfo': 'KOUN', 'region': 4},
    'KTWX': {'wfo': 'KTOP', 'region': 3},
    'KTYX': {'wfo': 'BKTV', 'region': 1},
    'KUDX': {'wfo': 'KUNR', 'region': 3},
    'KUEX': {'wfo': 'KGID', 'region': 3},
    'KVAX': {'wfo': 'KJAX', 'region': 2},
    'KVBX': {'wfo': 'KLOX', 'region': 6},
    'KVNX': {'wfo': 'KOUN', 'region': 4},
    'KVTX': {'wfo': 'KLOX', 'region': 6},
    'KVWX': {'wfo': 'KVWX', 'region': 3},
    'KYUX': {'wfo': 'KPSR', 'region': 5},
    'PABC': {'wfo': 'PAFC', 'region': 7},
    'PACG': {'wfo': 'PAJK', 'region': 7},
    'PAEC': {'wfo': 'PAFG', 'region': 7},
    'PAHG': {'wfo': 'PAFC', 'region': 7},
    'PAIH': {'wfo': 'PAFC', 'region': 7},
    'PAKC': {'wfo': 'PAFC', 'region': 7},
    'PAPD': {'wfo': 'PAFG', 'region': 7},
    'PGUA': {'wfo': 'PGUM', 'region': 6},
    'PHKI': {'wfo': 'PHFO', 'region': 0},
    'PHKM': {'wfo': 'PHFO', 'region': 0},
    'PHMO': {'wfo': 'PHFO', 'region': 0},
    'PHWA': {'wfo': 'PHFO', 'region': 0},
    'RKJK': {'wfo': 'RKJK', 'region': 6},
    'RKSW': {'wfo': 'RKSW', 'region': 6},
    'RODN': {'wfo': 'RODN', 'region': 6},
    'TADW': {'wfo': 'KLWX', 'region': 1},
    'TATL': {'wfo': 'KFFC', 'region': 2},
    'TBNA': {'wfo': 'KOHX', 'region': 4},
    'TBOS': {'wfo': 'KBOX', 'region': 1},
    'TBWI': {'wfo': 'KLWX', 'region': 1},
    'TCLT': {'wfo': 'KGSP', 'region': 2},
    'TCMH': {'wfo': 'KILN', 'region': 1},
    'TCVG': {'wfo': 'KILN', 'region': 1},
    'TDAL': {'wfo': 'KFWD', 'region': 4},
    'TDAY': {'wfo': 'KILN', 'region': 1},
    'TDCA': {'wfo': 'KLWX', 'region': 1},
    'TDEN': {'wfo': 'KBOU', 'region': 5},
    'TDFW': {'wfo': 'KFWD', 'region': 4},
    'TDTW': {'wfo': 'KDTX', 'region': 3},
    'TEWR': {'wfo': 'KOKX', 'region': 1},
    'TFLL': {'wfo': 'KMFL', 'region': 2},
    'THOU': {'wfo': 'KHGX', 'region': 4},
    'TIAD': {'wfo': 'KLWX', 'region': 1},
    'TIAH': {'wfo': 'KHGX', 'region': 4},
    'TICH': {'wfo': 'KICT', 'region': 3},
    'TIDS': {'wfo': 'KIND', 'region': 3},
    'TJFK': {'wfo': 'KOKX', 'region': 1},
    'TJUA': {'wfo': 'TSJU', 'region': 2},
    'TLAS': {'wfo': 'KVEF', 'region': 5},
    'TLAX': {'wfo': 'KLOX', 'region': 6},
    'TLGA': {'wfo': 'KOKX', 'region': 1},
    'TLVE': {'wfo': 'KCLE', 'region': 1},
    'TMCI': {'wfo': 'KEAX', 'region': 3},
    'TMCO': {'wfo': 'KMLB', 'region': 2},
    'TMDW': {'wfo': 'KLOT', 'region': 3},
    'TMEM': {'wfo': 'KMEG', 'region': 4},
    'TMIA': {'wfo': 'KMFL', 'region': 2},
    'TMKE': {'wfo': 'KMKX', 'region': 3},
    'TMSP': {'wfo': 'KMPX', 'region': 3},
    'TMSY': {'wfo': 'KHDC', 'region': 4},
    'TOKC': {'wfo': 'KOUN', 'region': 4},
    'TORD': {'wfo': 'KLOT', 'region': 3},
    'TPBI': {'wfo': 'KMFL', 'region': 2},
    'TPHL': {'wfo': 'KPHI', 'region': 1},
    'TPHX': {'wfo': 'KPSR', 'region': 5},
    'TPIT': {'wfo': 'KPBZ', 'region': 1},
    'TRDU': {'wfo': 'KRAH', 'region': 2},
    'TSDF': {'wfo': 'KLMK', 'region': 3},
    'TSEA': {'wfo': 'KSEW', 'region': 6},
    'TSFO': {'wfo': 'KMTR', 'region': 6},
    'TSJU': {'wfo': 'TJSJ', 'region': 2},
    'TSLC': {'wfo': 'KSLC', 'region': 5},
    'TSTL': {'wfo': 'KLSX', 'region': 3},
    'TTPA': {'wfo': 'KTBW', 'region': 2},
    'TTUL': {'wfo': 'KTSA', 'region': 4},
}


def find_local_file_name(path: str, radar_id: str, scan_time: datetime) -> str:
    radar_info = _radar_info[radar_id]
    iname = "%s_SDUS?%d_NVW%s_%s" % (radar_info['wfo'], radar_info['region'], radar_id[1:],
                                     scan_time.strftime("%Y%m%d%H%M"))
    matches = glob.glob(f'{path}/{iname}')
    if len(matches) == 0:
        raise FileNotFoundError(f"Couldn't find local file from {radar_id} at {scan_time: %Y-%m-%d %H%M} UTC")
    return matches[0]

def build_has_name(radar_id: str, scan_time: datetime) -> str:
    radar_info = _radar_info[radar_id]
    iname = "%s_SDUS3%d_NVW%s_%s" % (radar_info['wfo'], radar_info['region'], radar_id[1:],
                                     scan_time.strftime("%Y%m%d%H%M"))
    return iname


RADAR_NAMES = {
    'KABR': 'Aberdeen, SD',
    'KABX': 'Albuquerque, NM',
    'KAKQ': 'Wakefield, VA',
    'KAMA': 'Amarillo, TX',
    'KAMX': 'Miami, FL',
    'KAPX': 'Gaylord, MI',
    'KARX': 'La Crosse, WI',
    'KATX': 'Seattle, WA',
    'KBBX': 'Oroville, CA',
    'KBGM': 'Binghamton, NY',
    'KBHX': 'Eureka, CA',
    'KBIS': 'Bismarck, ND',
    'KBLX': 'Billings, MT',
    'KBMX': 'Birmingham, AL',
    'KBOX': 'Boston, MA',
    'KBRO': 'Brownsville, TX',
    'KBUF': 'Buffalo, NY',
    'KBYX': 'Key West, FL',
    'KCAE': 'Columbia, SC',
    'KCBW': 'Houlton, ME',
    'KCBX': 'Boise, ID',
    'KCCX': 'State College, PA',
    'KCLE': 'Cleveland, OH',
    'KCLX': 'Charleston, SC',
    'KCRP': 'Corpus Christi, TX',
    'KCXX': 'Burlington, VT',
    'KCYS': 'Cheyenne, WY',
    'KDAX': 'Sacramento, CA',
    'KDDC': 'Dodge City, KS',
    'KDFX': 'Laughlin AFB, TX',
    'KDGX': 'Jackson, MS',
    'KDIX': 'Philadelphia, PA',
    'KDLH': 'Duluth, MN',
    'KDMX': 'Des Moines, IA',
    'KDOX': 'Dover, DE',
    'KDTX': 'Detroit, MI',
    'KDVN': 'Davenport, IA',
    'KDYX': 'Abilene, TX',
    'KEAX': 'Kansas City, MO',
    'KEMX': 'Tucson, AZ',
    'KENX': 'Albany, NY',
    'KEOX': 'Fort Rucker, AL',
    'KEPZ': 'El Paso, TX',
    'KESX': 'Las Vegas, NV',
    'KEVX': 'Eglin AFB, FL',
    'KEWX': 'Austin, TX',
    'KEYX': 'Edwards AFB, CA',
    'KFCX': 'Roanoke, VA',
    'KFDR': 'Frederick, OK',
    'KFDX': 'Cannon AFB, NM',
    'KFFC': 'Atlanta, GA',
    'KFSD': 'Sioux Falls, SD',
    'KFSX': 'Flagstaff, AZ',
    'KFTG': 'Denver, CO',
    'KFWS': 'Dallas, TX',
    'KGGW': 'Glasgow, MT',
    'KGJX': 'Grand Junction, CO',
    'KGLD': 'Goodland, KS',
    'KGRB': 'Green Bay, WI',
    'KGRK': 'Fort Hood, TX',
    'KGRR': 'Grand Rapids, MI',
    'KGSP': 'Greenville, SC',
    'KGWX': 'Columbus AFB, MS',
    'KGYX': 'Portland, ME',
    'KHDC': 'Hammond, LA',
    'KHDX': 'Holloman AFB, NM',
    'KHGX': 'Houston, TX',
    'KHNX': 'Hanford, CA',
    'KHPX': 'Fort Campbell, KY',
    'KHTX': 'Huntsville, AL',
    'KICT': 'Wichita, KS',
    'KICX': 'Cedar City, UT',
    'KILN': 'Wilmington, OH',
    'KILX': 'Lincoln, IL',
    'KIND': 'Indianapolis, IN',
    'KINX': 'Tulsa, OK',
    'KIWA': 'Phoenix, AZ',
    'KIWX': 'Fort Wayne, IN',
    'KJAX': 'Jacksonville, FL',
    'KJGX': 'Macon, GA',
    'KJKL': 'Jackson, KY',
    'KLBB': 'Lubbock, TX',
    'KLCH': 'Lake Charles, LA',
    'KLGX': 'Langley Hill, WA',
    'KLNX': 'North Platte, NE',
    'KLOT': 'Chicago, IL',
    'KLRX': 'Elko, NV',
    'KLSX': 'St. Louis, MO',
    'KLTX': 'Wilmington, NC',
    'KLVX': 'Louisville, KY',
    'KLWX': 'Sterling, VA',
    'KLZK': 'Little Rock, AR',
    'KMAF': 'Midland, TX',
    'KMAX': 'Medford, OR',
    'KMBX': 'Minot, ND',
    'KMHX': 'Morehead City, NC',
    'KMKX': 'Milwaukee, WI',
    'KMLB': 'Melbourne, FL',
    'KMOB': 'Mobile, AL',
    'KMPX': 'Minneapolis, MN',
    'KMQT': 'Marquette, MI',
    'KMRX': 'Morristown, TN',
    'KMSX': 'Missoula, MT',
    'KMTX': 'Salt Lake City, UT',
    'KMUX': 'San Francisco, CA',
    'KMVX': 'Grand Forks, ND',
    'KMXX': 'Montgomery, AL',
    'KNKX': 'San Diego, CA',
    'KNQA': 'Memphis, TN',
    'KOAX': 'Omaha, NE',
    'KOHX': 'Nashville, TN',
    'KOKX': 'New York City, NY',
    'KOTX': 'Spokane, WA',
    'KPAH': 'Paducah, KY',
    'KPBZ': 'Pittsburgh, PA',
    'KPDT': 'Pendleton, OR',
    'KPOE': 'Fort Polk, LA',
    'KPUX': 'Pueblo, CO',
    'KRAX': 'Raleigh, NC',
    'KRGX': 'Reno, NV',
    'KRIW': 'Riverton, WY',
    'KRLX': 'Charleston, WV',
    'KRTX': 'Portland, OR',
    'KSFX': 'Pocatello, ID',
    'KSGF': 'Springfield, MO',
    'KSHV': 'Shreveport, LA',
    'KSJT': 'San Angelo, TX',
    'KSOX': 'Santa Ana Mountains, CA',
    'KSRX': 'Fort Smith, AR',
    'KTBW': 'Tampa, FL',
    'KTFX': 'Great Falls, MT',
    'KTLH': 'Tallahassee, FL',
    'KTLX': 'Oklahoma City, OK',
    'KTWX': 'Topeka, KS',
    'KTYX': 'Montague, NY',
    'KUDX': 'Rapid City, SD',
    'KUEX': 'Hastings, NE',
    'KVAX': 'Moody AFB, GA',
    'KVBX': 'Vandenberg AFB, CA',
    'KVNX': 'Vance AFB, OK',
    'KVTX': 'Los Angeles, CA',
    'KVWX': 'Evansville, IN',
    'KYUX': 'Yuma, AZ',
    'PABC': 'Bethel, AK',
    'PACG': 'Sitka, AK',
    'PAEC': 'Nome, AK',
    'PAHG': 'Anchorage, AK',
    'PAIH': 'Middleton Island, AK',
    'PAKC': 'King Salmon, AK',
    'PAPD': 'Fairbanks, AK',
    'PHKI': 'Kauai, HI',
    'PHKM': 'Kamuela, HI',
    'PHMO': 'Molokai, HI',
    'PHWA': 'South Point, HI',
    'PGUA': 'Guam',
    'RKJK': 'Kunsan AB, South Korea',
    'RKSW': 'Osan AB, South Korea',
    'RODN': 'Kadena AB, Japan',
    'TADW': 'Washington, DC',
    'TATL': 'Atlanta, GA',
    'TBNA': 'Nashville, TN',
    'TBOS': 'Boston, MA',
    'TBWI': 'Baltimore, MD',
    'TCLT': 'Charlotte, NC',
    'TCMH': 'Columbus, OH',
    'TCVG': 'Cincinnati, OH',
    'TDAL': 'Dallas, TX',
    'TDAY': 'Dayton, OH',
    'TDCA': 'Washington, DC',
    'TDEN': 'Denver, CO',
    'TDFW': 'Dallas, TX',
    'TDTW': 'Detroit, MI',
    'TEWR': 'Newark, NJ',
    'TFLL': 'Fort Lauderdale, FL',
    'THOU': 'Houston, TX',
    'TIAD': 'Washington, DC',
    'TIAH': 'Houston, TX',
    'TICH': 'Wichita, KS',
    'TIDS': 'Indianapolis, IN',
    'TJFK': 'New York, NY',
    'TJUA': 'San Juan, PR',
    'TLAS': 'Las Vegas, NV',
    'TLAX': 'Los Angeles, CA',
    'TLGA': 'New York, NY',
    'TLVE': 'Cleveland, OH',
    'TMCI': 'Kansas City, MO',
    'TMCO': 'Orlando, FL',
    'TMDW': 'Chicago, IL',
    'TMEM': 'Memphis, TN',
    'TMIA': 'Miami, FL',
    'TMKE': 'Milwaukee, WI',
    'TMSP': 'Minneapolis, MN',
    'TMSY': 'New Orleans, LA',
    'TOKC': 'Oklahoma City, OK',
    'TORD': 'Chicago, IL',
    'TPBI': 'West Palm Beach, FL',
    'TPHL': 'Philadelphia, PA',
    'TPHX': 'Phoenix, AZ',
    'TPIT': 'Pittsburgh, PA',
    'TRDU': 'Raleigh, NC',
    'TSDF': 'Louisville, KY',
    'TSEA': 'Seattle, WA',
    'TSFO': 'San Francisco, CA',
    'TSJU': 'San Juan, PR',
    'TSLC': 'Salt Lake City, UT',
    'TSTL': 'St. Louis, MO',
    'TTPA': 'Tampa, FL',
    'TTUL': 'Tulsa, OK',
}
